// Extension message and recorded-action types — no UI deps (safe for service worker).

export const ACTION_TYPE = {
  CLICK: "CLICK",
  INPUT: "INPUT",
  SUBMIT: "SUBMIT",
} as const;

export const RUNTIME_MESSAGE_TYPE = {
  START_RECORDING: "START_RECORDING",
  STOP_RECORDING: "STOP_RECORDING",
  REPLAY_ACTIONS: "REPLAY_ACTIONS",
  ACTION_CAPTURED: "ACTION_CAPTURED",
  GET_RECORDING_STATE: "GET_RECORDING_STATE",
  REPLAY_COMPLETE: "REPLAY_COMPLETE",
  REPLAY_FAILED: "REPLAY_FAILED",
  RECORDING_COMPLETE: "RECORDING_COMPLETE",
  CAPTURE_SELECTION: "CAPTURE_SELECTION",
  SELECTION_CAPTURED: "SELECTION_CAPTURED",
  START_CAPTURE: "START_CAPTURE",
  STOP_CAPTURE: "STOP_CAPTURE",
  PING: "PING",
  TAB_SWITCHED: "TAB_SWITCHED",
} as const;
